spring:
  jpa:
    properties:
      hibernate:
        search:
          backend:
            type: lucene
            directory.root: ./.data/index
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:h2:file:./.data/database"

management:
  endpoints:
    web:
      exposure:
        include:
          - load-data
#  endpoint:
#    shutdown:
#      enabled=true:

#logging:
#  level:
#    org.hibernate: DEBUG
