spring:
  jpa:
    properties:
      hibernate:
        search:
          backend:
            type: lucene
            directory.root: ./.data/index
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:sqlite:.sample.db"
  config:
    import: optional:file:.secrets.yml

management:
  endpoints:
    web:
      exposure:
        include:
          - data-load
          - data-index
#  endpoint:
#    shutdown:
#      enabled=true:

#logging:
#  level:
#    org.hibernate: DEBUG
